class FormatAgent:

    def format_report(self, report_text: str):

        formatted_report = f"""
        SAFETY REPORT
        ------------------------
        {report_text}
        ------------------------
        Generated by AI Safety Platform
        """

        return {
            "status": "success",
            "formatted_report": formatted_report
        }